name = "iapubweb"
main = "worker.js"
compatibility_date = "2024-01-01"

[assets]
directory = "./src"

[[kv_namespaces]]
binding = "USERS_KV"
id = "9497356c6f5d44fe917809a5889e94cf"

# Variables d'environnement à définir dans le dashboard Cloudflare Workers :
# OPENROUTER_KEY, PEXELS_KEY, RESEND_KEY, ANTHROPIC_KEY
# wrangler secret put ANTHROPIC_KEY
